services:
  frontend:
    build:
      context: .
      target: dev
    env_file:
      - path: .env
        required: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - frontend-node-modules:/app/node_modules
      - frontend-next:/app/.next

volumes:
  frontend-node-modules:
  frontend-next:
