services:
  backend:
    build:
      context: .
      target: dev
    env_file:
      - path: .env
        required: true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
