import type { Question, Requirement } from "./types";

export const requirements: Requirement[] = [
  {
    id: "async",
    title: "Асинхронность в Python",
    mandatory: true,
    checkType: "open",
    questionRef: "В3",
    structureHint: "контекст · ваша роль · решение · чему научило",
    whatWeCheck: "Умение локализовать причину в асинхронном коде и закрыть ресурс безопасно.",
    strongAnswer: "Называет причину, личное действие и способ проверки.",
    weakAnswer: "Описывает только симптом или говорит «перезапустили».",
    followUpRule: "ЕСЛИ не назван способ проверки → спросить: «Как вы убедились, что утечка не вернётся?»",
    coverage: [0, 0, 1, 0, 0],
  },
  {
    id: "sql",
    title: "Проектирование БД и SQL",
    mandatory: true,
    checkType: "verifiable",
    questionRef: "В5",
    structureHint: "",
    whatWeCheck: "Корректный запрос, индекс и понимание нагрузки.",
    strongAnswer: "Оконная функция и индекс под фильтр.",
    weakAnswer: "SELECT * без объяснения плана.",
    followUpRule: "",
    coverage: [0, 0, 0, 0, 1],
  },
  {
    id: "ownership",
    title: "Личный вклад в проект",
    mandatory: true,
    checkType: "open",
    questionRef: "В1",
    structureHint: "контекст · ваша роль · решение · чему научило",
    whatWeCheck: "Граница личной ответственности, не описание команды целиком.",
    strongAnswer: "Называет свою часть, ограничения и компромисс.",
    weakAnswer: "Говорит «мы сделали» без своей роли.",
    followUpRule: "ЕСЛИ граница команды не названа → спросить про зону ответственности.",
    coverage: [1, 0, 0, 0, 0],
  },
  {
    id: "incident",
    title: "Разбор инцидента",
    mandatory: true,
    checkType: "open",
    questionRef: "В4",
    structureHint: "контекст · ваша роль · решение · чему научило",
    whatWeCheck: "Причина, личное действие и проверка результата после исправления.",
    strongAnswer: "Называет причину, действие и способ проверки.",
    weakAnswer: "Только симптом.",
    followUpRule: "ЕСЛИ способ проверки не назван → спросить: «Как вы убедились, что проблема не вернётся?»",
    coverage: [0, 0, 0, 1, 0],
  },
  {
    id: "celery",
    title: "Celery и фоновые задачи",
    mandatory: true,
    checkType: "open",
    questionRef: "-",
    structureHint: "контекст · ваша роль · решение · чему научило",
    whatWeCheck: "Практический опыт с очередями и воркерами.",
    strongAnswer: "Очередь, ретраи, идемпотентность.",
    weakAnswer: "Только название библиотеки.",
    followUpRule: "",
    coverage: [0, 0, 0, 0, 0],
  },
  {
    id: "testing",
    title: "Тестирование",
    mandatory: true,
    checkType: "open",
    questionRef: "В2",
    structureHint: "контекст · ваша роль · решение · чему научило",
    whatWeCheck: "Граница модульных и интеграционных тестов.",
    strongAnswer: "Моки внешних API, интеграция на тестовой базе.",
    weakAnswer: "«Пишем тесты» без уровней.",
    followUpRule: "",
    coverage: [0, 1, 0, 0, 0],
  },
  {
    id: "docker",
    title: "Docker",
    mandatory: false,
    checkType: "open",
    questionRef: "В2",
    structureHint: "контекст · ваша роль · решение · чему научило",
    whatWeCheck: "Сборка окружения для сервиса.",
    strongAnswer: "Образ, сеть, тома.",
    weakAnswer: "Только docker run.",
    followUpRule: "",
    coverage: [0, 1, 0, 0, 0],
  },
];

export const questions: Question[] = [
  {
    index: 1,
    type: "open",
    text: "Расскажите о проекте, где вы лично отвечали за миграцию или крупное изменение. Что было вашей зоной, а что делала команда?",
    altText: "Опишите задачу, которую вы вели сами от начала до результата. Где заканчивалась ваша ответственность?",
    prepLimitSec: 120,
    answerLimitSec: 240,
    requirementIds: ["ownership"],
    followUpRule: "",
    followUpText: "",
    structureHint: "контекст · ваша роль · решение · чему научило",
  },
  {
    index: 2,
    type: "open",
    text: "Как вы решаете, что мокать в тестах, а что проверять интеграционно? Приведите пример из сервиса с внешней зависимостью.",
    altText: "Опишите тестовую пирамиду на вашем последнем сервисе. Что осталось интеграционным и почему?",
    prepLimitSec: 120,
    answerLimitSec: 240,
    requirementIds: ["testing", "docker"],
    followUpRule: "",
    followUpText: "",
    structureHint: "контекст · ваша роль · решение · чему научило",
  },
  {
    index: 3,
    type: "open",
    text: "Расскажите о ситуации, когда асинхронный код в Python создал проблему. Что пошло не так и как вы это решили?",
    altText: "Вспомните утечку соединений, зависание event loop или гонку в async-коде. Как вы это нашли и закрыли?",
    prepLimitSec: 120,
    answerLimitSec: 240,
    requirementIds: ["async"],
    followUpRule: "Если способ проверки не назван, задать уточнение.",
    followUpText:
      "Вы упомянули, что добавили контекстный менеджер. Как вы убедились, что утечка не вернётся?",
    structureHint: "контекст · ваша роль · решение · чему научило",
  },
  {
    index: 4,
    type: "open",
    text: "Разберите инцидент на проде: как поняли причину, что сделали сами и как проверили, что исправление сработало?",
    altText: "Опишите ночной сбой сервиса. Какие шаги вы прошли от симптома до проверки после фикса?",
    prepLimitSec: 120,
    answerLimitSec: 240,
    requirementIds: ["incident"],
    followUpRule: "",
    followUpText: "",
    structureHint: "контекст · ваша роль · решение · чему научило",
  },
  {
    index: 5,
    type: "sql",
    text: "Нужен рейтинг заказов внутри категории за день. Какой SQL вы напишете и какой индекс поставите?",
    altText: "Как посчитать топ внутри группы по дате, не уходя в полное сканирование таблицы?",
    prepLimitSec: 60,
    answerLimitSec: 120,
    requirementIds: ["sql"],
    followUpRule: "",
    followUpText: "",
    structureHint: "",
  },
];

export const practiceQuestion = {
  text: "Расскажите об инструменте, которым пользуетесь каждый день, и почему выбрали его.",
  structureHint: "контекст · ваша роль · решение · чему научило",
};

export function getQuestion(index: number): Question | undefined {
  return questions.find((item) => item.index === index);
}

export function getRequirement(id: string): Requirement | undefined {
  return requirements.find((item) => item.id === id);
}
